<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DotNetFoundryLLM.ModelFormats.Gguf</RootNamespace>
    <AssemblyName>DotNetFoundryLLM.ModelFormats.Gguf</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DotNetFoundryLLM.Abstractions/DotNetFoundryLLM.Abstractions.csproj" />
    <ProjectReference Include="../DotNetFoundryLLM.Tensors/DotNetFoundryLLM.Tensors.csproj" />
  </ItemGroup>
</Project>
